[global]
   workgroup = WORKGROUP
   server string = LibraryIT Server
   security = user
   map to guest = never

   log file = /logs/access.log
   max log size = 1000
   logging = file

# =========================
# EBOOKS
# =========================

[ebooks]
   path = /libraryit/ebooks
   browseable = yes
   read only = no

   valid users = @staff @readonly
   write list = @staff

   create mask = 0770
   directory mask = 0770

# =========================
# PAPERS
# =========================

[papers]
   path = /libraryit/papers
   browseable = yes
   read only = no

   valid users = @staff @readonly
   write list = @staff

   create mask = 0770
   directory mask = 0770

# =========================
# DOCS
# =========================

[docs]
   path = /libraryit/docs
   browseable = yes
   read only = yes

   valid users = member contributor librarian
   write list = librarian

   create mask = 0774
   directory mask = 0774

# =========================
# SOURCECODE
# =========================

[sourcecode]
   path = /libraryit/sourcecode
   browseable = no
   read only = yes

   valid users = @staff
   write list = contributor librarian

   create mask = 0750
   directory mask = 0750
